### ISSUE TITLE
Sometimes the lingo check runs/hangs forever

### ISSUE THREAD

**Issue by natefinch** [codelingo/codelingo#130]
![image](https://user-images.githubusercontent.com/3185864/47241534-0e2ce080-d3ba-11e8-922f-dd9d6ea71437.png)

It would be great to have a place to go look at the progress of the running tenets, and stop/restart them.  But I'd settle for it not just running forever. 

Actually... *is* there a way to stop a running check on github? I don't see any UI for it.

**Comment by waigani** [comment]
We have some basic commands you fire off as comments on the PR e.g. /ignore (ignores an issue) /review (reruns the review). Should be pretty easy to add in a /cancel-review cmd.

There's a dashboard in the pipeline that'll give you the controls & visibility you're after.

Out of interest what's the LOC of the repo you're running? If vendor's committed, it's worth ignoring it:

```
# .codelingoignore file
vendor/
```

**Comment by natefinch** [comment]
it's only 40k LOC if you exclude vendor (which we don't check in)
