### ISSUE TITLE
Structs broken in Playground

### ISSUE THREAD

**Issue by rstorr** [codelingo/codelingo#140]
```go
package main

import (
	"fmt"
)

type Thing struct {
    name       string
    generation int
    model      string
}

func main() {
  thing = Thing{name: “Raspberry Pi”, generation: 2, model: “B”}
}

```

Generating queries from the above code takes user to blank page. Error in console is:

 Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.

Didn't see any output on slack errors channel.

**Comment by emersonwood** [comment]
The example code is not valid Go code and the query gen was throwing an error. The error was trying to be rendered in a broken component which has since been fixed.
