### ISSUE TITLE
Tenet: fmt-verbs. Waiting on ability to use variables in any_of (see example)

### ISSUE THREAD

**Issue by Daanikus** [codelingo/codelingo#238]
```
any_of:
  go.ident:
    name as typeName
  go.star_expr:
    go.ident:
      name as typeName
```

**Comment by BlakeMScurr** [comment]
In practice I see`unary_expr` (`&`) much more often than `star_expr` (`*`), so it'd be good to add that too. Also, an argument can be a function call, and I think that should cover it.
