### ISSUE TITLE
Unable to install flows on Windows 10.

### ISSUE THREAD

**Issue by CallanTaylor** [codelingo/codelingo#303]
When running "lingo install review" or "lingo install rewrite" on Windows, the message "zip: not a valid zip file" is returned and the flow is not installed

**Comment by VinayKashyap15** [comment]
> 
> 
> When running "lingo install review" or "lingo install rewrite" on Windows, the message "zip: not a valid zip file" is returned and the flow is not installed

Did you find a solution? I am experiencing the same error.

**Comment by victorwitkamp** [comment]
Same issue here as well
