### ISSUE TITLE
Long comments break CLQL query generation

### ISSUE THREAD

**Issue by GhostNappa** [codelingo/codelingo#334]
Using the playground (and sublime extension) I have found that comments of a certain length cause the query generator to silently fail and produce an incorrect result when the selected code is placed under these comments.

Here is an example: https://www.codelingo.io/playground/?id=32

In each comment the "b" marks the point at which the length causes the query generator to break.
In the example highlight the defined function (lines 2 and 3, NOT including the comment) and generate the query, try it with and without the "b" in the comment.

It seems to work when you include the comment in your selection. But it should work either way, right?

**Comment by kindblakey** [comment]
Hi @GhostNappa!

Thanks for your detailed bug report! What output did you get? How do you know it's incorrect? I've tried to follow your steps by going to your python example https://www.codelingo.io/playground/?id=32, selecting everything, and generating a query. I got:
```
import codelingo/ast/python36

python36.file(depth = any):
  @playground.highlight
  python36.module:
    python36.function_def:
      python36.arguments:
        kwarg == "None"
        vararg == "None"
      python36.expr:
        python36.call:
          python36.name:
            python36.load
```

Is this the same result you got? I'm not confident that it's incorrect, but I'll do a little more digging.

**Comment by kindblakey** [comment]
Also, @GhostNappa can you please describe the steps to reproduce this in sublime or the CLI (if you're familiar with the `lingo tooling query-from-offset` command)? That should help me to eliminate several variables that could be at play in the playground.

**Comment by GhostNappa** [comment]
To recreate in sublime with python:
```
#aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab
def helloWorld():
    print("hello world!")
```

Generating a query with only the function selected, this is my output:
```
import codelingo/ast/python36

python36.file(depth = any)
```

Generating again when selecting all code, including the comment:
```
import codelingo/ast/python36

python36.file(depth = any):
  python36.module:
    python36.function_def:
      python36.arguments
      python36.expr:
        python36.call:
          python36.name:
            python36.load
          python36.str
    python36.expr:
      python36.call:
        python36.name:
          python36.load
```

Removing the "b" and again only selecting function, not the comment:
```
import codelingo/ast/python36

python36.file(depth = any):
  python36.module:
    python36.expr:
      python36.call:
        python36.name:
          python36.load
```
