### ISSUE TITLE
CLQL query not generated for nested function that is declared below other code within enclosing function

### ISSUE THREAD

**Issue by GhostNappa** [codelingo/codelingo#335]
Highlight only the nested function (lines 4 and 5) in this example to see the generated query is not complete.

https://www.codelingo.io/playground/?id=33

It looks like it works fine if the function is directly nested, i.e by removing the print statement of the enclosing function from above the nested function. I expect either should work though.

**Comment by kindblakey** [comment]
@GhostNappa thanks for your detailed bug report, yet again 😄 

I've recreated and confirmed that this is a bug. I generated this clearly incomplete query:
```
import codelingo/ast/python36

@playground.highlight
python36.file(depth = any)
```

I'm on it.
