### ISSUE TITLE
Error in lint go repo

### ISSUE THREAD

**Issue by arthurkiller** [codelingo/codelingo#338]
**Check the debug tree for other required information**

<details>
<summary>Bug Type</summary>

+  <details><summary>Playground</summary>

    https://github.com/meitu/titan/pull/59#pullrequestreview-208880511
---

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
**Additional context**

**Comment by Daanikus** [comment]
Thanks for this @arthurkiller
