### ISSUE TITLE
Failing after 32s — 0 issues found before hitting an error.

### ISSUE THREAD

**Issue by thrasher-** [codelingo/codelingo#478]
**Describe the bug**
When CodeLingo reviews our PRs, it mentions the text in the above title.

**To Reproduce**
Example PR: https://github.com/thrasher-corp/gocryptotrader/pull/376. This seems to happen on all of them as of recent

**Expected behavior**
For it to report a result (pass or issue(s))

**Comment by thrasher-** [comment]
Hey guys, any update?

**Comment by BlakeMScurr** [comment]
Hey @thrasher-, yeah we've narrowed it down to a GRPC connectivity issue, specifically to our db. More updates should be forthcoming.
